# Generated by Django 5.2.4 on 2025-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_bookcalendar_created_by_bookcalendar_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcalendar",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="timezone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bookcalendar",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookcalendar",
            name="html_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookcalendar",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
