# Generated by Django 5.2.4 on 2025-11-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_blogcategory_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsubscribe",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailsubscribe",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
