# Generated by Django 5.2.4 on 2025-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_emailsubscribe_deleted_emailsubscribe_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcalendar",
            name="event_id",
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="attendees",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="event_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="summary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
