# Generated by Django 5.2.4 on 2025-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0005_remove_bookcalendar_event_id_bookcalendar_attendees_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookcalendar",
            old_name="html_link",
            new_name="book_link",
        ),
        migrations.AddField(
            model_name="bookcalendar",
            name="meet_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
