# Generated by Django 5.2.4 on 2025-11-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_bookcalendar_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcalendar",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="bookmeet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="frequentlyaskedquestion",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="subject",
        ),
    ]
