# Generated by Django 5.2.4 on 2025-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_remove_blogpost_excerpt_privacypolicy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="message",
            new_name="about",
        ),
        migrations.RenameField(
            model_name="contactmessage",
            old_name="email",
            new_name="business_email",
        ),
        migrations.RenameField(
            model_name="contactmessage",
            old_name="full_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="budget",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="current_problem",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="investment_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOOTSTRAPPED", "Bootsrapped or Self-funded"),
                    ("PRE-SEED", "Pre-Seed"),
                    ("SEED", "Seed"),
                    ("SERIES_A", "Series A"),
                    ("SERIES_B", "Series B"),
                    ("SERIES_C", "Series C"),
                    ("SERIES_D", "Series D"),
                    ("IPO", "IPO"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="BookMeet",
        ),
    ]
