# Generated by Django 5.2.4 on 2025-11-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_chatwindow_screenshotimage_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwindow",
            name="analysis_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
