# Generated by Django 5.2.4 on 2025-12-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_waitlist_delete_wishlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitlist",
            options={"ordering": ["-created_at"]},
        ),
    ]
