# Generated by Django 5.2.4 on 2025-12-21 11:12

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="video_file",
            field=models.FileField(upload_to=backend.models.video_upload_path),
        ),
    ]
